-- ════════════════════════════════════════════════════════════════
--  PrimeBet — Schema do banco (PostgreSQL / Supabase)
--  Rode no Supabase: Dashboard → SQL Editor → cole tudo → Run.
-- ════════════════════════════════════════════════════════════════

-- ───────────────── AFILIADOS ─────────────────
create table if not exists public.afiliados (
  id            bigint generated by default as identity primary key,
  nome          text not null,
  comissao_pct  numeric(5,2) not null default 0,   -- % sobre a comissão da banca
  criado_em     timestamptz not null default now()
);

-- ───────────────── CLIENTES (jogadores) ─────────────────
create table if not exists public.clientes (
  id                     bigint generated by default as identity primary key,
  nome                   text not null unique,        -- usado no login e no mapa de grupos
  senha_hash             text,                        -- hash da senha do jogador (nunca texto puro)
  ativo                  boolean not null default true,
  calcao                 numeric(12,2) not null default 0,
  desconto               numeric(6,2)  not null default 0,
  comissao_pct           numeric(5,2)  not null default 0,   -- % de comissão da banca sobre o ganho
  afiliado_id            bigint references public.afiliados(id) on delete set null,
  afiliado_comissao_pct  numeric(5,2)  not null default 0,   -- % do afiliado sobre a comissão
  link                   text,                              -- URL única de acesso do jogador (ex: /xxxx/NOME)
  criado_em              timestamptz not null default now()
);

alter table public.clientes add column if not exists link text;
alter table public.apostas  add column if not exists advertencia text;
alter table public.apostas  alter column odd type numeric(12,2);

-- ───────────────── APOSTAS (bilhetes) ─────────────────
create table if not exists public.apostas (
  id                  bigint generated by default as identity primary key,
  cliente_id          bigint not null references public.clientes(id) on delete cascade,
  data                timestamptz not null default now(),
  jogo                text not null,
  odd                 numeric(12,2) not null default 0,  -- 0 = em aberto (suporta odds de múltiplas acumuladas)
  valor               numeric(12,2) not null default 0,  -- 0 = em aberto
  status              text not null default 'EM ABERTO'
                        check (status in ('EM ABERTO','GREEN','MEIO GREEN','MEIO RED','RED','REEMBOLSO')),
  casa                text default '',                   -- descarrego (BET365, BETANO, ...)
  -- calculados (preenchidos pelo trigger abaixo):
  saldo_bruto         numeric(12,2) not null default 0,
  comissao            numeric(12,2) not null default 0,
  comissao_afiliado   numeric(12,2) not null default 0,
  saldo_liquido       numeric(12,2) not null default 0,
  -- flags operacionais:
  baixa_liquidez      boolean not null default false,
  advertido           boolean not null default false,
  advertencia         text,                              -- texto da advertência/observação
  irregular           boolean not null default false,
  em_aberto_odd       boolean not null default false,
  em_aberto_valor     boolean not null default false,
  -- origem / rastreio:
  origem              text not null default 'manual' check (origem in ('manual','whatsapp')),
  grupo_id            text,                             -- JID do grupo (...@g.us) quando veio do bot
  criado_em           timestamptz not null default now(),
  atualizado_em       timestamptz not null default now()
);

create index if not exists apostas_cliente_idx on public.apostas(cliente_id);
create index if not exists apostas_data_idx    on public.apostas(data desc);
create index if not exists apostas_status_idx  on public.apostas(status);

-- ───────────────── MOTOR DE CÁLCULO (mesma fórmula do painel) ─────────────────
-- Saldo Bruto: GREEN= val*(odd-1) | MEIO GREEN= metade | RED= -val | MEIO RED= -val/2 | resto= 0
-- Comissão: % da banca sobre o ganho (só quando saldo bruto > 0)
-- Comissão Afiliado: % do afiliado sobre a comissão
-- Saldo Líquido: bruto - comissão - comissão afiliado
create or replace function public.calc_aposta()
returns trigger
language plpgsql
as $$
declare
  c_com  numeric(5,2) := 0;
  c_af   numeric(5,2) := 0;
  c_desc numeric(6,2) := 0;
  odd_ef numeric(12,2);
  sb     numeric(12,2);
  cm     numeric(12,2);
  caf    numeric(12,2);
begin
  select comissao_pct, afiliado_comissao_pct, desconto into c_com, c_af, c_desc
  from public.clientes where id = new.cliente_id;

  -- odd efetiva = odd - desconto do cliente (ex.: 2,00 - 0,01 = 1,99). Nunca negativa.
  odd_ef := greatest(new.odd - coalesce(c_desc, 0), 0);

  sb := case new.status
          when 'GREEN'      then new.valor * (odd_ef - 1)
          when 'MEIO GREEN' then new.valor * (odd_ef - 1) / 2
          when 'RED'        then -new.valor
          when 'MEIO RED'   then -new.valor / 2
          else 0
        end;

  cm  := case when sb > 0 then sb * (coalesce(c_com,0) / 100) else 0 end;
  caf := cm * (coalesce(c_af,0) / 100);

  new.saldo_bruto       := round(sb, 2);
  new.comissao          := round(cm, 2);
  new.comissao_afiliado := round(caf, 2);
  new.saldo_liquido     := round(sb - cm - caf, 2);

  new.em_aberto_odd   := (new.odd = 0);
  new.em_aberto_valor := (new.valor = 0);
  new.atualizado_em   := now();
  return new;
end;
$$;

drop trigger if exists trg_calc_aposta on public.apostas;
create trigger trg_calc_aposta
  before insert or update on public.apostas
  for each row execute function public.calc_aposta();

-- ───────────────── SEGURANÇA (RLS) ─────────────────
-- Ativa RLS sem políticas públicas: o acesso é feito pelo servidor Next
-- usando a service_role key (que ignora RLS). O cliente do navegador NÃO
-- lê/grava direto — passa sempre pela API do Next. Políticas finas por
-- papel (admin/operador/jogador) entram numa etapa posterior.
alter table public.afiliados enable row level security;
alter table public.clientes  enable row level security;
alter table public.apostas   enable row level security;
