-- ════════════════════════════════════════════════════════════════
--  PrimeBet — Migração 003: Conferência de grupos
--  Registra TODA imagem recebida nos grupos para auditar o que foi
--  (ou não) transcrito. Rode no SQL Editor ou via pooler. Idempotente.
-- ════════════════════════════════════════════════════════════════

create table if not exists public.imagens_recebidas (
  id          bigint generated by default as identity primary key,
  grupo_id    text not null,                                   -- JID do grupo (...@g.us)
  grupo_nome  text,
  cliente_id  bigint references public.clientes(id) on delete set null,  -- null = grupo sem cliente (config errada)
  msg_id      text not null unique,                            -- id da mensagem (liga com a reação)
  remetente   text,                                            -- nome/numero de quem enviou
  enviado_em  timestamptz not null default now(),
  thumb_path  text,                                            -- caminho da miniatura no Storage (bucket conferencia)
  reagida     boolean not null default false,                  -- recebeu uma reação de gatilho
  lancada     boolean not null default false,                  -- virou aposta no painel
  ignorada    boolean not null default false,                  -- operador marcou como "não é bilhete / ok"
  emoji       text,
  aposta_id   bigint references public.apostas(id) on delete set null,
  criado_em   timestamptz not null default now()
);

create index if not exists imgrec_grupo_idx on public.imagens_recebidas(grupo_id);
create index if not exists imgrec_pend_idx  on public.imagens_recebidas(reagida, ignorada);
create index if not exists imgrec_data_idx  on public.imagens_recebidas(enviado_em desc);

-- Resumo por grupo (recebidas / transcritas / pendentes) para a tela de Conferência.
create or replace function public.conferencia_grupos(p_dt1 date default null, p_dt2 date default null)
returns json language sql stable as $$
  select coalesce(json_agg(g order by g.pendentes desc, g.grupo_nome), '[]'::json) from (
    select
      grupo_id,
      max(grupo_nome)                                          as grupo_nome,
      bool_or(cliente_id is not null)                          as tem_cliente,
      count(*)                                                 as recebidas,
      count(*) filter (where reagida)                          as transcritas,
      count(*) filter (where not reagida and not ignorada)     as pendentes
    from public.imagens_recebidas
    where (p_dt1 is null or enviado_em::date >= p_dt1)
      and (p_dt2 is null or enviado_em::date <= p_dt2)
    group by grupo_id
  ) g;
$$;
