-- ════════════════════════════════════════════════════════════════
--  PrimeBet — Migração 006: FUNDAÇÃO MULTI-BANCA (SaaS white-label)
--  Cada "banca" é um tenant isolado. PrimeBet vira a 1ª banca.
--  Esta migração só adiciona estrutura + backfill — não altera o
--  comportamento atual (com 1 banca, tudo continua funcionando).
-- ════════════════════════════════════════════════════════════════

-- 1) Tabela de bancas (tenants)
create table if not exists public.bancas (
  id            bigint generated by default as identity primary key,
  slug          text not null unique,                 -- subdomínio/identificador (ex.: 'primebet')
  nome          text not null,
  dominio       text unique,                          -- domínio próprio (ex.: 'primebet.com'), opcional
  logo_url      text,
  cor_primaria  text not null default '#DAA520',      -- cor de destaque
  cor_fundo     text not null default '#13200a',      -- cor de fundo do tema
  ativo         boolean not null default true,
  criado_em     timestamptz not null default now()
);

-- 2) PrimeBet como a primeira banca
insert into public.bancas (slug, nome, logo_url, cor_primaria, cor_fundo)
values ('primebet', 'PrimeBet', '/logo.jpg', '#DAA520', '#13200a')
on conflict (slug) do nothing;

-- 3) banca_id em todas as tabelas de dados
alter table public.clientes          add column if not exists banca_id bigint references public.bancas(id) on delete cascade;
alter table public.afiliados         add column if not exists banca_id bigint references public.bancas(id) on delete cascade;
alter table public.apostas           add column if not exists banca_id bigint references public.bancas(id) on delete cascade;
alter table public.imagens_recebidas add column if not exists banca_id bigint references public.bancas(id) on delete cascade;

-- 4) Backfill: tudo que já existe pertence à PrimeBet
update public.clientes          set banca_id = (select id from public.bancas where slug='primebet') where banca_id is null;
update public.afiliados         set banca_id = (select id from public.bancas where slug='primebet') where banca_id is null;
update public.apostas           set banca_id = (select id from public.bancas where slug='primebet') where banca_id is null;
update public.imagens_recebidas set banca_id = (select id from public.bancas where slug='primebet') where banca_id is null;

-- 5) Agora exige banca_id (não pode haver dado órfão)
alter table public.clientes          alter column banca_id set not null;
alter table public.afiliados         alter column banca_id set not null;
alter table public.apostas           alter column banca_id set not null;
alter table public.imagens_recebidas alter column banca_id set not null;

-- 6) Índices por banca (consultas serão sempre escopadas)
create index if not exists clientes_banca_idx          on public.clientes(banca_id);
create index if not exists afiliados_banca_idx         on public.afiliados(banca_id);
create index if not exists apostas_banca_idx           on public.apostas(banca_id);
create index if not exists imagens_recebidas_banca_idx on public.imagens_recebidas(banca_id);

-- 7) Nome do cliente passa a ser único POR BANCA (não mais global).
--    Remove a unique global em clientes(nome), seja qual for o nome da constraint.
do $$
declare cn text;
begin
  select conname into cn from pg_constraint
   where conrelid='public.clientes'::regclass and contype='u'
     and pg_get_constraintdef(oid) ilike '%(nome)%';
  if cn is not null then execute format('alter table public.clientes drop constraint %I', cn); end if;
end $$;

create unique index if not exists clientes_banca_nome_idx on public.clientes(banca_id, lower(nome));
