-- ════════════════════════════════════════════════════════════════
--  PrimeBet — Migração 007: Despesas (documentação semanal)
--  Mensagens "descrição: valor" no grupo "despesa" viram despesas,
--  com a data da mensagem. Tela própria no painel (não entra no
--  cálculo do fechamento por enquanto).
-- ════════════════════════════════════════════════════════════════

create table if not exists public.despesas (
  id          bigint generated by default as identity primary key,
  banca_id    bigint not null references public.bancas(id) on delete cascade,
  descricao   text not null,
  valor       numeric(12,2) not null default 0,
  data        timestamptz not null default now(),   -- data da mensagem (define a semana)
  grupo_id    text,
  grupo_nome  text,
  msg_id      text unique,                           -- evita duplicar a mesma mensagem
  criado_em   timestamptz not null default now()
);

create index if not exists despesas_banca_data_idx on public.despesas(banca_id, data desc);
