-- ════════════════════════════════════════════════════════════════
--  PrimeBet — Migração 021: Equipe (cargos) + Auditoria (histórico)
--  • equipe    : usuários gestor/operador (o admin/dono segue no Supabase Auth).
--  • auditoria : registra QUEM alterou cada bilhete (status, odd, valor, etc.).
--  Idempotente. Rode no SQL Editor. RLS ligado, sem policy pública:
--  só o service-role (server) enxerga — nunca vaza pro cliente.
-- ════════════════════════════════════════════════════════════════

-- ── Equipe: gestor e operador ───────────────────────────────────
create table if not exists public.equipe (
  id            bigint generated by default as identity primary key,
  nome          text not null,                                   -- login (usado no /login)
  senha_hash    text not null,                                   -- scrypt (salt:hash) — NUNCA texto puro
  papel         text not null check (papel in ('gestor', 'operador')),
  ativo         boolean not null default true,
  criado_em     timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);
-- Login único e sem depender de maiúscula/minúscula (evita "Joao" e "joao" colidindo,
-- e conflito com o 'admin' reservado — barrado na aplicação).
create unique index if not exists equipe_nome_lower_idx on public.equipe (lower(nome));

alter table public.equipe enable row level security;

-- ── Auditoria: quem mexeu em cada bilhete ───────────────────────
-- SEM FK para apostas de propósito: o histórico precisa SOBREVIVER à exclusão do
-- bilhete (inclusive registrar QUEM excluiu). aposta_id fica como referência solta.
create table if not exists public.auditoria (
  id         bigint generated by default as identity primary key,
  aposta_id  bigint,                                             -- bilhete afetado (sem FK: sobrevive à exclusão)
  ator_tipo  text not null,                                      -- 'admin' | 'gestor' | 'operador'
  ator_nome  text not null,                                      -- login de quem fez
  acao       text not null,                                      -- 'lancamento','status','odd','valor','jogo','data','contestacao','exclusao',...
  campo      text,                                               -- campo alterado (quando se aplica)
  de         text,                                               -- valor anterior (texto legível)
  para       text,                                               -- valor novo (texto legível)
  criado_em  timestamptz not null default now()
);
create index if not exists auditoria_aposta_idx on public.auditoria (aposta_id, criado_em desc);

alter table public.auditoria enable row level security;
