-- ════════════════════════════════════════════════════════════════
--  PrimeBet — Migração 022: Envio de PDF de fechamento nos grupos
--  O painel gera o PDF (mesmo que o admin baixa), sobe no Storage e cria um
--  pedido aqui; o BOT pega, baixa e manda como documento no grupo do cliente.
--  Idempotente. RLS ligado (só service-role: web e bot).
-- ════════════════════════════════════════════════════════════════

create table if not exists public.envios_pdf (
  id            bigint generated by default as identity primary key,
  grupo_id      text not null,                              -- JID do grupo do cliente (...@g.us)
  cliente_nome  text,
  storage_path  text not null,                              -- caminho do PDF no bucket 'fechamentos'
  legenda       text,                                       -- mensagem que acompanha o PDF
  status        text not null default 'pendente',           -- pendente | enviado | erro
  erro          text,
  criado_em     timestamptz not null default now(),
  enviado_em    timestamptz
);
create index if not exists envios_pdf_status_idx on public.envios_pdf (status, criado_em);
alter table public.envios_pdf enable row level security;

-- Bucket privado onde o painel sobe os PDFs (o bot baixa via service-role).
insert into storage.buckets (id, name, public)
values ('fechamentos', 'fechamentos', false)
on conflict (id) do nothing;
