-- ═══════════════════════════════════════════════════════════════════
--  028 · Acertos (controle de pagamentos/recebimentos dos clientes)
--
--  Camada de acompanhamento POR CIMA do que já existe. NÃO toca em aposta
--  nem em fechamento — só registra os MOVIMENTOS de dinheiro que os donos
--  dão baixa contra o saldo líquido de cada cliente no período:
--    • cliente GANHOU (saldo líq. > 0) -> a banca PAGA   -> tipo 'pago'
--    • cliente PERDEU (saldo líq. < 0) -> a banca RECEBE  -> tipo 'recebido'
--
--  O saldo devido vem SEMPRE do banco (fechamento_clientes, ao vivo); esta
--  tabela guarda só o que foi efetivamente pago/recebido, com quem lançou
--  e quando (histórico). Pendente = |saldo líq.| − soma dos movimentos.
--
--  RLS ligada, sem policy pública: só o service-role (server) enxerga.
-- ═══════════════════════════════════════════════════════════════════

create table if not exists public.acertos (
  id         bigint generated by default as identity primary key,
  banca_id   bigint not null references public.bancas(id) on delete cascade,
  cliente_id bigint not null references public.clientes(id) on delete cascade,
  dt1        date not null,                                   -- período liquidado (início)
  dt2        date not null,                                   -- período liquidado (fim)
  tipo       text not null check (tipo in ('pago', 'recebido')),
  valor      numeric not null check (valor > 0),
  obs        text,
  ator_tipo  text,                                            -- quem lançou (papel)
  ator_nome  text,                                            -- quem lançou (login)
  criado_em  timestamptz not null default now()
);

create index if not exists acertos_cli_periodo_idx on public.acertos (cliente_id, dt1, dt2);

alter table public.acertos enable row level security;
